INSERT INTO TABLE_GENERATOR(IID,GEN_NAME,GEN_VALUE) values(1,'USER_ENTITY_PK',10000000);
--INSERT INTO USER_TABLE(NNAME,PPASSWORD) VALUES('firstuser','gwfirst');
--INSERT INTO USER_TABLE(NNAME,PPASSWORD) VALUES('seconduser','gwsecond');